#!/usr/bin/env bash
# telling the story of passwd
while IFS=: read -r username password uid gid fullname homedir shell; do
	echo "the user $username is part of the $gid gang, lives in $homedir and rides $shell. USER ID's place is protected by the passcode $password, more info about the user here: $fullname"
done
