#!/bin/bash

# add a counter
counter=1

# start the loop
while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
		echo "Best School"
	fi
	counter=$((counter + 1))
done
