#!/usr/bin/env bash
# using while loop to display numbers 0 threw 12 and 1 to 59

hour=0
minute=1

while [ $hour -le 12 ]
do
	echo "hour: $hour"

	while [ $minute -le 59 ]
	do
		echo "$minute"
	
		minute=$((minute + 1))
	done

	minute=1
	hour=$((hour + 1 ))
done
