#!/usr/bin/env bash
# listing the contents of the current directory in list format

current_dir=$(dirname "$0")

cd "$current_dir" || cd ... || exit |...

for file in *; do
	if [[ ! $file == .* && $file == *-* ]]; then

		name=${file#*-}

		echo "$name"
	fi
done
